[package]
name = "rust-rtps"
version = "0.1.0"
authors = ["Joao Rebelo <2730147+jrebelo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdr = {git= "https://github.com/s2e-systems/cdr-rs"}
serde = "1.0"
serde_derive = "1.0"
num-derive = "0.3"
rand = "0.7" # For GUID generation
ipconfig = "0.2"
net2 = "0.2"

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies.num]
version = "0.2"
default-features = false